### PR TITLE
Fixes #108

### LINKED ISSUE #108: Add Instructions for Setting up User Secrets in Read Me
Double check any other needed steps to setting up the services locally are also on there

### PR DESCRIPTION
**Pull request by kjacobsen16**
- Adds instructions on how to set up user secrets (DB credentials)
- Also adds more information about how to deploy to a server

@amedenblik  I figured you can review this pull request by using the new read me to set up the services locally. I'll assign you to a couple issues and plan a meeting with you and Harper.

### CODE REVIEW

**Comment by amedenblik** [comment]
I received this error after pressing the green play button: `error NU1104: Unable to find project 'C:\Users\anstewar\Documents\projects\streamstats\newfolder\NSSServices\Shared\Shared.csproj'. Check that the project reference is valid and that the project file exists.` ([info on error NU1104](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1104))

I checked GageStatsServices.csproj and see this: 
```
  <ItemGroup>
    <ProjectReference Include="..\..\NSSServices\Shared\Shared.csproj" />
    <ProjectReference Include="..\GageStatsAgent\GageStatsAgent.csproj" />
    <ProjectReference Include="..\GageStatsDB\GageStatsDB.csproj" />
  </ItemGroup>
```

The issue is that the NSSServices folder is not located in the project. I was able to resolve the error by following the [NSSServices README instructions](https://github.com/USGS-WiM/NSSServices#readme) first. I will update the GageStatsServices README so that users install NSSServices first.

**Comment by amedenblik** [comment]
- Dead link: [WIM.Services.GageStats NuGet package](https://www.nuget.org/packages/WIM.Services.GageStats/)

**Review by amedenblik — APPROVED** [review]
@kjacobsen16 I made a small change. Will you please take a look before I merge?

**Comment by kjacobsen16** [comment]
@amedenblik thanks for figuring that out! I forgot you need the NSSServices 😅

**Pull request merged**
